corpus: 'swb'
model_name: 'hc_ctc'
seed: 1111
distributed:
        node_rank: null
        world_size: null
        ddp: null
        gpu_num: 2
        gpus: 2
        nnodes: 1
features:
        downsample: 8
        n_mels: 80
        sample_rate: 16000
        wav_len: 30
        fmask: 27
model:
        vocab_size: null
        inter_vocab_size: null
        dropout: 0.1
        headDim: 64
        hidDim: 512
        n_layer: 24
        nhead: 8
        conv_kernel_size: 9
        num_ctc: 4
trainer:
        reset_iterations: True
        iterations_done: 0
        epochs_done: 0
        nepochs: 15
        bsz_small: 32
        batch_size: 128
        base_batch_size: 128
        clip: 1.0
        base_lr: 4e-5
        lr: null
        anneal_strategy: 'linear'
        pct_start: 0.3
        div_factor: 10
        final_div_factor: 1e12
        load_opt: False
        load_sch: False
        log_after: 10
paths:
        save_path: '/research/nfs_fosler_1/vishal/saved_models/${model_name}_all_then_${corpus}_H${model.hidDim}L${model.n_layer}DS${features.downsample}E${trainer.nepochs}.pth.tar'
        ckpt_path: '/research/nfs_fosler_1/vishal/saved_models/hc_ctc_all_H512L24DS8E48.pth.tar'
        train_path: '/research/nfs_fosler_1/vishal/text/swb300/swb_ms98_transcriptions/swb300_aug.csv'
        test_path: ''
        decode_path: ''
        tokenizer_path: '/research/nfs_fosler_1/vishal/text/tokenizers/saved/tokenizer_all_32768.json'
        inter_tokenizer_paths: ['/research/nfs_fosler_1/vishal/text/tokenizers/saved/tokenizer_all_512.json',
                                  '/research/nfs_fosler_1/vishal/text/tokenizers/saved/tokenizer_all_2048.json',
                                  '/research/nfs_fosler_1/vishal/text/tokenizers/saved/tokenizer_all_8192.json',
                                  '/research/nfs_fosler_1/vishal/text/tokenizers/saved/tokenizer_all_32768.json']
        logging_file: 'logs/${model_name}_all_then_${corpus}_H${model.hidDim}L${model.n_layer}DS${features.downsample}E${trainer.nepochs}.log'
        summary_path: 'summary/${model_name}_all_then_${corpus}_H${model.hidDim}L${model.n_layer}DS${features.downsample}E${trainer.nepochs}'
